# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alex/Dokumente/Programmieren/PyDSF/ui/mainwindow.ui'
#
# Created: Tue Oct 30 14:57:02 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(352, 548)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_experiment = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_experiment.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_experiment.setFlat(False)
        self.groupBox_experiment.setCheckable(False)
        self.groupBox_experiment.setObjectName(_fromUtf8("groupBox_experiment"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_experiment)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_instrument = QtGui.QLabel(self.groupBox_experiment)
        self.label_instrument.setObjectName(_fromUtf8("label_instrument"))
        self.gridLayout.addWidget(self.label_instrument, 0, 0, 1, 1)
        self.comboBox_instrument = QtGui.QComboBox(self.groupBox_experiment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_instrument.sizePolicy().hasHeightForWidth())
        self.comboBox_instrument.setSizePolicy(sizePolicy)
        self.comboBox_instrument.setObjectName(_fromUtf8("comboBox_instrument"))
        self.comboBox_instrument.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_instrument, 0, 1, 1, 1)
        self.groupBox_data = QtGui.QGroupBox(self.groupBox_experiment)
        self.groupBox_data.setEnabled(True)
        self.groupBox_data.setObjectName(_fromUtf8("groupBox_data"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_data)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listWidget_data = QtGui.QListWidget(self.groupBox_data)
        self.listWidget_data.setAlternatingRowColors(True)
        self.listWidget_data.setObjectName(_fromUtf8("listWidget_data"))
        self.gridLayout_4.addWidget(self.listWidget_data, 0, 0, 1, 1)
        self.buttonBox_open = QtGui.QDialogButtonBox(self.groupBox_data)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox_open.sizePolicy().hasHeightForWidth())
        self.buttonBox_open.setSizePolicy(sizePolicy)
        self.buttonBox_open.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox_open.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_open.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.buttonBox_open.setCenterButtons(False)
        self.buttonBox_open.setObjectName(_fromUtf8("buttonBox_open"))
        self.gridLayout_4.addWidget(self.buttonBox_open, 0, 1, 1, 1)
        self.groupBox_replicates = QtGui.QGroupBox(self.groupBox_data)
        self.groupBox_replicates.setCheckable(True)
        self.groupBox_replicates.setChecked(False)
        self.groupBox_replicates.setObjectName(_fromUtf8("groupBox_replicates"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_replicates)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioButton_rep_files = QtGui.QRadioButton(self.groupBox_replicates)
        self.radioButton_rep_files.setEnabled(False)
        self.radioButton_rep_files.setChecked(True)
        self.radioButton_rep_files.setObjectName(_fromUtf8("radioButton_rep_files"))
        self.gridLayout_3.addWidget(self.radioButton_rep_files, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_replicates, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_data, 1, 0, 1, 2)
        self.groupBox_temp = QtGui.QGroupBox(self.groupBox_experiment)
        self.groupBox_temp.setEnabled(True)
        self.groupBox_temp.setAutoFillBackground(False)
        self.groupBox_temp.setCheckable(False)
        self.groupBox_temp.setObjectName(_fromUtf8("groupBox_temp"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_temp)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_tmin = QtGui.QLabel(self.groupBox_temp)
        self.label_tmin.setObjectName(_fromUtf8("label_tmin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_tmin)
        self.doubleSpinBox_tmin = QtGui.QDoubleSpinBox(self.groupBox_temp)
        self.doubleSpinBox_tmin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_tmin.setDecimals(1)
        self.doubleSpinBox_tmin.setProperty("value", 25.0)
        self.doubleSpinBox_tmin.setObjectName(_fromUtf8("doubleSpinBox_tmin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_tmin)
        self.label_tmax = QtGui.QLabel(self.groupBox_temp)
        self.label_tmax.setObjectName(_fromUtf8("label_tmax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_tmax)
        self.doubleSpinBox_tmax = QtGui.QDoubleSpinBox(self.groupBox_temp)
        self.doubleSpinBox_tmax.setDecimals(1)
        self.doubleSpinBox_tmax.setProperty("value", 95.0)
        self.doubleSpinBox_tmax.setObjectName(_fromUtf8("doubleSpinBox_tmax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_tmax)
        self.label_dt = QtGui.QLabel(self.groupBox_temp)
        self.label_dt.setObjectName(_fromUtf8("label_dt"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_dt)
        self.doubleSpinBox_dt = QtGui.QDoubleSpinBox(self.groupBox_temp)
        self.doubleSpinBox_dt.setDecimals(1)
        self.doubleSpinBox_dt.setProperty("value", 1.0)
        self.doubleSpinBox_dt.setObjectName(_fromUtf8("doubleSpinBox_dt"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_dt)
        self.gridLayout.addWidget(self.groupBox_temp, 2, 0, 1, 1)
        self.groupBox_cutoff = QtGui.QGroupBox(self.groupBox_experiment)
        self.groupBox_cutoff.setEnabled(True)
        self.groupBox_cutoff.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_cutoff.setCheckable(True)
        self.groupBox_cutoff.setChecked(False)
        self.groupBox_cutoff.setObjectName(_fromUtf8("groupBox_cutoff"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_cutoff)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_cutoff_high = QtGui.QLabel(self.groupBox_cutoff)
        self.label_cutoff_high.setObjectName(_fromUtf8("label_cutoff_high"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_cutoff_high)
        self.doubleSpinBox_upper = QtGui.QDoubleSpinBox(self.groupBox_cutoff)
        self.doubleSpinBox_upper.setPrefix(_fromUtf8(""))
        self.doubleSpinBox_upper.setDecimals(1)
        self.doubleSpinBox_upper.setObjectName(_fromUtf8("doubleSpinBox_upper"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_upper)
        self.label_cutoff_low = QtGui.QLabel(self.groupBox_cutoff)
        self.label_cutoff_low.setObjectName(_fromUtf8("label_cutoff_low"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_cutoff_low)
        self.doubleSpinBox_lower = QtGui.QDoubleSpinBox(self.groupBox_cutoff)
        self.doubleSpinBox_lower.setDecimals(1)
        self.doubleSpinBox_lower.setObjectName(_fromUtf8("doubleSpinBox_lower"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_lower)
        self.gridLayout.addWidget(self.groupBox_cutoff, 2, 1, 1, 1)
        self.groupBox_signal_threshold = QtGui.QGroupBox(self.groupBox_experiment)
        self.groupBox_signal_threshold.setEnabled(True)
        self.groupBox_signal_threshold.setCheckable(True)
        self.groupBox_signal_threshold.setChecked(False)
        self.groupBox_signal_threshold.setObjectName(_fromUtf8("groupBox_signal_threshold"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_signal_threshold)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.spinBox_signal_threshold = QtGui.QSpinBox(self.groupBox_signal_threshold)
        self.spinBox_signal_threshold.setMaximum(1000000)
        self.spinBox_signal_threshold.setObjectName(_fromUtf8("spinBox_signal_threshold"))
        self.verticalLayout.addWidget(self.spinBox_signal_threshold)
        self.gridLayout.addWidget(self.groupBox_signal_threshold, 3, 0, 1, 1)
        self.groupBox_cbar = QtGui.QGroupBox(self.groupBox_experiment)
        self.groupBox_cbar.setEnabled(True)
        self.groupBox_cbar.setCheckable(True)
        self.groupBox_cbar.setChecked(False)
        self.groupBox_cbar.setObjectName(_fromUtf8("groupBox_cbar"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_cbar)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_cbar_start = QtGui.QLabel(self.groupBox_cbar)
        self.label_cbar_start.setObjectName(_fromUtf8("label_cbar_start"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_cbar_start)
        self.doubleSpinBox_cbar_start = QtGui.QDoubleSpinBox(self.groupBox_cbar)
        self.doubleSpinBox_cbar_start.setDecimals(1)
        self.doubleSpinBox_cbar_start.setObjectName(_fromUtf8("doubleSpinBox_cbar_start"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_cbar_start)
        self.label_cbar_end = QtGui.QLabel(self.groupBox_cbar)
        self.label_cbar_end.setObjectName(_fromUtf8("label_cbar_end"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_cbar_end)
        self.doubleSpinBox_cbar_end = QtGui.QDoubleSpinBox(self.groupBox_cbar)
        self.doubleSpinBox_cbar_end.setDecimals(1)
        self.doubleSpinBox_cbar_end.setObjectName(_fromUtf8("doubleSpinBox_cbar_end"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_cbar_end)
        self.gridLayout.addWidget(self.groupBox_cbar, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_experiment, 0, 0, 1, 1)
        self.buttonBox_process = QtGui.QDialogButtonBox(self.centralWidget)
        self.buttonBox_process.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_process.setObjectName(_fromUtf8("buttonBox_process"))
        self.gridLayout_2.addWidget(self.buttonBox_process, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 352, 24))
        self.menuBar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/qtlogo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label_instrument.setBuddy(self.comboBox_instrument)
        self.label_tmin.setBuddy(self.doubleSpinBox_tmin)
        self.label_tmax.setBuddy(self.doubleSpinBox_tmax)
        self.label_dt.setBuddy(self.doubleSpinBox_dt)
        self.label_cutoff_high.setBuddy(self.doubleSpinBox_upper)
        self.label_cutoff_low.setBuddy(self.doubleSpinBox_lower)
        self.label_cbar_start.setBuddy(self.doubleSpinBox_cbar_start)
        self.label_cbar_end.setBuddy(self.doubleSpinBox_cbar_end)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyDSF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_experiment.setTitle(QtGui.QApplication.translate("MainWindow", "Experimental Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_instrument.setText(QtGui.QApplication.translate("MainWindow", "Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_instrument.setItemText(0, QtGui.QApplication.translate("MainWindow", "Analytik Jena qTOWER 2.0/2.2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_data.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Add data files to the experiment. If multiple files are loaded, they are treated as replicates.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_data.setTitle(QtGui.QApplication.translate("MainWindow", "Data File", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_replicates.setTitle(QtGui.QApplication.translate("MainWindow", "Replicates", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_rep_files.setText(QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_temp.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Temperature range of the data points. Only applies, if the data file does not contain any temperature information.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_temp.setTitle(QtGui.QApplication.translate("MainWindow", "Temperature settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tmin.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">min</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_tmin.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tmax.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">max</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_tmax.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_dt.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>&Delta;T</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_dt.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_cutoff.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Only T<span style=\" vertical-align:sub;\">m</span> values within this limit are considered valid.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_cutoff.setTitle(QtGui.QApplication.translate("MainWindow", "Cutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cutoff_high.setText(QtGui.QApplication.translate("MainWindow", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_upper.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cutoff_low.setText(QtGui.QApplication.translate("MainWindow", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_lower.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_signal_threshold.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>If the signal exceeds this threshold, the coresponding well is assumed to be denatured.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_signal_threshold.setTitle(QtGui.QApplication.translate("MainWindow", "Signal Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_cbar.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Defines the range of the colorbar used for the T<span style=\" vertical-align:sub;\">m</span> heatmap.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_cbar.setTitle(QtGui.QApplication.translate("MainWindow", "Colorbar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cbar_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_cbar_start.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cbar_end.setText(QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_cbar_end.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))

#import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

